#!/usr/bin/env php
<?php

define('ADEPLOYER_VERSION', '1.0');

if (version_compare('5.4.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        'A-Deployer requires PHP 5.4.' . PHP_EOL
    );
    die(1);
}
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

define('COMPOSER_INSTALL', __DIR__ . '/vendor/autoload.php');

if (!defined('COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require COMPOSER_INSTALL;
try {
    $aDeployer = new Antwerpes\ADeployer\Runner();
    $aDeployer->run();
} catch (Exception $e) {
    echo $e->getMessage();
}